server:
  port: 8088
  #上下文访问路径
  servlet:
    context-path: /im_bird_sys
    # 配置Tomcat编码,默认为UTF-8
spring:
  datasource:
    name: im_bird_sys
    #采用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #连接数据库
    url: jdbc:mysql:///im_bird?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    #监控统计
    filters: stat
    initial-size: 2
    max-idle: 10
    min-idle: 1
    max_active: 20
    max-wait: 60000
    time-between-evict-runs-mills: 60000
    min-evictable-time-mills: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
